### ISSUE TITLE
Fix date in YODA reference

### ISSUE THREAD

**Issue by mih** [datalad/datalad-paper-joss#87] opened 2021-04-21 07:15 UTC
2011 cannot be.

**Comment by bpoldrack** [comment] 2021-04-21 08:34
2018 according to https://f1000research.com/posters/7-1965

**Comment by bpoldrack** [comment] 2021-04-21 08:41
We currently link https://github.com/myyoda/myyoda which was created only this year. A bit strange to then give the year the poster was published. I don't know - what do we link?

**Comment by yarikoptic** [comment] 2021-04-21 12:50
Thanks for spotting.  Indeed 2021 not 2011 was intended ;) pushed the fix

**Closed as completed** 2021-04-21 12:50 UTC
